# Generated by Django 5.2.9 on 2025-12-15 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_inquiry", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DentalKnowledgeArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="标题")),
                (
                    "question_pattern",
                    models.CharField(
                        blank=True,
                        help_text="用于简单检索的关键词或典型问句",
                        max_length=255,
                        null=True,
                        verbose_name="典型问题模式",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="逗号分隔，如：龋齿,根管治疗",
                        max_length=255,
                        null=True,
                        verbose_name="标签",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "牙科知识文章",
                "verbose_name_plural": "牙科知识文章",
                "db_table": "dental_knowledge_article",
            },
        ),
        migrations.AlterModelOptions(
            name="inquiry",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "AI问询（旧）",
                "verbose_name_plural": "AI问询（旧）",
            },
        ),
        migrations.CreateModel(
            name="AIChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "Assistant")],
                        max_length=16,
                        verbose_name="角色",
                    ),
                ),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 对话消息",
                "verbose_name_plural": "AI 对话消息",
                "db_table": "ai_chat_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIRecommendationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_question", models.TextField(verbose_name="原始问题")),
                (
                    "structured_intent",
                    models.JSONField(
                        blank=True,
                        help_text='例如 {"disease_category": "龋齿", "recommended_department": "口腔内科"}',
                        null=True,
                        verbose_name="解析后意图",
                    ),
                ),
                (
                    "recommended_doctors",
                    models.JSONField(
                        blank=True,
                        help_text="存 doctor_id 列表及关键字段，方便后续分析",
                        null=True,
                        verbose_name="推荐医生列表",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recommendation_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 推荐记录",
                "verbose_name_plural": "AI 推荐记录",
                "db_table": "ai_recommendation_log",
            },
        ),
    ]
