# Generated by Django 5.2.9 on 2025-12-27 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_inquiry", "0002_initial"),
        ("doctors", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dentalknowledgearticle",
            name="embedding",
            field=models.JSONField(
                blank=True,
                help_text="存储文本的向量表示，用于语义检索",
                null=True,
                verbose_name="文本向量",
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialty_preference",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="用户对不同专科的偏好程度",
                        verbose_name="专科偏好",
                    ),
                ),
                (
                    "hospital_preference",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="用户对不同医院的偏好程度",
                        verbose_name="医院偏好",
                    ),
                ),
                (
                    "price_sensitivity",
                    models.FloatField(
                        default=0.5,
                        help_text="0-1，0表示不敏感，1表示非常敏感",
                        verbose_name="价格敏感度",
                    ),
                ),
                (
                    "time_preference",
                    models.CharField(
                        blank=True,
                        help_text="morning, afternoon, evening",
                        max_length=20,
                        null=True,
                        verbose_name="时间偏好",
                    ),
                ),
                (
                    "doctor_feature_preference",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='{"score_weight": 0.6, "reviews_weight": 0.4}',
                        verbose_name="医生特征偏好",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户画像",
                "verbose_name_plural": "用户画像",
                "db_table": "user_profile",
            },
        ),
        migrations.CreateModel(
            name="UserBehavior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("search", "搜索"),
                            ("click_doctor", "点击医生"),
                            ("view_doctor_detail", "查看医生详情"),
                            ("make_appointment", "预约医生"),
                            ("cancel_appointment", "取消预约"),
                            ("rate_doctor", "评价医生"),
                            ("click_recommendation", "点击推荐医生"),
                        ],
                        max_length=50,
                        verbose_name="行为类型",
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="记录行为发生时的上下文，如搜索关键词、推荐来源等",
                        verbose_name="上下文信息",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        default=1.0,
                        help_text="行为的评分，用于推荐算法计算",
                        verbose_name="行为评分",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_behaviors",
                        to="doctors.doctor",
                        verbose_name="相关医生",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behaviors",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户行为记录",
                "verbose_name_plural": "用户行为记录",
                "db_table": "user_behavior",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "action", "created_at"],
                        name="user_behavi_user_id_85f9e6_idx",
                    ),
                    models.Index(
                        fields=["doctor", "action"],
                        name="user_behavi_doctor__e5f9a2_idx",
                    ),
                ],
            },
        ),
    ]
