# Generated by Django 5.2.9 on 2025-12-08 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctors", "0001_initial"),
        ("hospitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateField(verbose_name="预约日期")),
                (
                    "appointment_time",
                    models.CharField(max_length=5, verbose_name="预约时间"),
                ),
                (
                    "symptoms",
                    models.TextField(blank=True, null=True, verbose_name="症状描述"),
                ),
                (
                    "patient_name",
                    models.CharField(max_length=50, verbose_name="患者姓名"),
                ),
                (
                    "patient_phone",
                    models.CharField(max_length=11, verbose_name="患者电话"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "待就诊"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                            ("checked-in", "已签到"),
                        ],
                        default="upcoming",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "checkin_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="签到时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "预约",
                "verbose_name_plural": "预约",
                "db_table": "appointment",
                "ordering": ["-appointment_date", "-appointment_time"],
                "unique_together": {("doctor", "appointment_date", "appointment_time")},
            },
        ),
    ]
