# Generated by Django 5.2.9 on 2025-12-26 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0002_initial"),
        ("doctors", "0001_initial"),
        ("hospitals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="就诊日期")),
                ("diagnosis", models.TextField(verbose_name="诊断")),
                ("content", models.TextField(verbose_name="病历内容")),
                (
                    "treatment",
                    models.TextField(blank=True, null=True, verbose_name="治疗方案"),
                ),
                (
                    "medications",
                    models.JSONField(blank=True, default=list, verbose_name="药物列表"),
                ),
                (
                    "result_image",
                    models.URLField(blank=True, null=True, verbose_name="结果图片URL"),
                ),
                (
                    "rated",
                    models.BooleanField(default=False, verbose_name="是否已评价"),
                ),
                (
                    "rating",
                    models.IntegerField(blank=True, null=True, verbose_name="评分"),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="评价内容"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="record",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="doctors.doctor",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="hospitals.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name": "病历",
                "verbose_name_plural": "病历",
                "db_table": "record",
                "ordering": ["-created_at"],
            },
        ),
    ]
