# Generated by Django 5.2.9 on 2025-12-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="医院名称")),
                ("address", models.CharField(max_length=200, verbose_name="地址")),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="纬度"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="经度"),
                ),
                (
                    "image",
                    models.URLField(blank=True, null=True, verbose_name="图片URL"),
                ),
                ("rating", models.FloatField(default=0.0, verbose_name="评分")),
                (
                    "review_count",
                    models.IntegerField(default=0, verbose_name="评价数量"),
                ),
                ("description", models.TextField(blank=True, verbose_name="简介")),
                (
                    "business_hours",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="营业时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "医院",
                "verbose_name_plural": "医院",
                "db_table": "hospital",
                "ordering": ["-rating", "-review_count"],
            },
        ),
    ]
