# Generated by Django 5.2.9 on 2025-12-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_add_visit_count'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hospital',
            new_name='hospital_visit_c_b4bd25_idx',
            old_name='hospitals_h_visit_count_idx',
        ),
    ]
