# Generated by Django 5.2.9 on 2025-12-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_rename_hospitals_h_visit_count_idx_hospital_visit_c_b4bd25_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='hospital',
            name='hospital_visit_c_b4bd25_idx',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='visit_count',
        ),
    ]
