# Generated by Django 5.2.9 on 2025-12-08 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                ("title", models.CharField(max_length=50, verbose_name="职称")),
                ("specialty", models.CharField(max_length=50, verbose_name="专科")),
                ("avatar", models.URLField(blank=True, null=True, verbose_name="头像")),
                ("score", models.FloatField(default=0.0, verbose_name="评分")),
                ("reviews", models.IntegerField(default=0, verbose_name="评价数量")),
                ("introduction", models.TextField(blank=True, verbose_name="简介")),
                (
                    "education",
                    models.CharField(blank=True, max_length=100, verbose_name="学历"),
                ),
                (
                    "experience",
                    models.CharField(blank=True, max_length=200, verbose_name="经验"),
                ),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="是否在线"),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="是否为管理员"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="hospitals.hospital",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "医生",
                "verbose_name_plural": "医生",
                "db_table": "doctor",
                "ordering": ["-score", "-reviews"],
            },
        ),
    ]
