# Generated by Django 5.2.9 on 2025-12-26 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hospitals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="排班日期")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "有效"), ("cancelled", "已取消")],
                        default="active",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "排班",
                "verbose_name_plural": "排班",
                "db_table": "doctor_schedule",
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                ("title", models.CharField(max_length=50, verbose_name="职称")),
                ("specialty", models.CharField(max_length=50, verbose_name="专科")),
                ("avatar", models.URLField(blank=True, null=True, verbose_name="头像")),
                ("score", models.FloatField(default=0.0, verbose_name="评分")),
                ("reviews", models.IntegerField(default=0, verbose_name="评价数量")),
                ("introduction", models.TextField(blank=True, verbose_name="简介")),
                (
                    "education",
                    models.CharField(blank=True, max_length=100, verbose_name="学历"),
                ),
                (
                    "experience",
                    models.CharField(blank=True, max_length=200, verbose_name="经验"),
                ),
                (
                    "is_online",
                    models.BooleanField(default=False, verbose_name="是否在线"),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="是否为管理员"),
                ),
                (
                    "audit_status",
                    models.CharField(
                        choices=[
                            ("pending", "待审核"),
                            ("approved", "已通过"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申请时间"),
                ),
                (
                    "audited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审核时间"
                    ),
                ),
                (
                    "rejected_reason",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="拒绝原因"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="hospitals.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name": "医生",
                "verbose_name_plural": "医生",
                "db_table": "doctor",
                "ordering": ["-score", "-reviews"],
            },
        ),
    ]
