# Generated by Django 5.2.9 on 2025-12-26 08:28

from django.conf import settings
from django.db import migrations, models, connection


def check_field_exists(table_name, field_name):
    """检查字段是否已存在"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = %s 
            AND COLUMN_NAME = %s
        """, [table_name, field_name])
        return cursor.fetchone()[0] > 0


def check_constraint_exists(constraint_name):
    """检查约束是否已存在"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.TABLE_CONSTRAINTS 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND CONSTRAINT_NAME = %s
        """, [constraint_name])
        return cursor.fetchone()[0] > 0


def migrate_forward(apps, schema_editor):
    """前向迁移：如果字段已存在则跳过"""
    # 检查字段是否已存在
    start_time_exists = check_field_exists('doctor_schedule', 'start_time')
    end_time_exists = check_field_exists('doctor_schedule', 'end_time')
    max_appointments_exists = check_field_exists('doctor_schedule', 'max_appointments')
    constraint_exists = check_constraint_exists('unique_doctor_schedule_per_day')
    
    # 如果字段已存在，说明数据库表结构已经正确，只需要更新Django状态
    # 这里不需要实际修改数据库，因为字段已经存在


def migrate_backward(apps, schema_editor):
    """反向迁移"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_initial"),
        ("hospitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={
                "ordering": ["-date", "start_time", "-created_at"],
                "verbose_name": "排班",
                "verbose_name_plural": "排班",
            },
        ),
        migrations.RunPython(migrate_forward, migrate_backward),
        # 使用SeparateDatabaseAndState来只更新Django状态，不修改数据库
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name="schedule",
                    name="unique_doctor_schedule_per_day",
                ),
                migrations.AddField(
                    model_name="schedule",
                    name="end_time",
                    field=models.CharField(
                        default="08:30",
                        help_text="格式：HH:mm，如 08:30",
                        max_length=5,
                        verbose_name="结束时间",
                    ),
                ),
                migrations.AddField(
                    model_name="schedule",
                    name="max_appointments",
                    field=models.IntegerField(default=3, verbose_name="该时间段最多预约数"),
                ),
                migrations.AddField(
                    model_name="schedule",
                    name="start_time",
                    field=models.CharField(
                        default="08:00",
                        help_text="格式：HH:mm，如 08:00",
                        max_length=5,
                        verbose_name="开始时间",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="schedule",
                    constraint=models.UniqueConstraint(
                        fields=("doctor", "date", "start_time"),
                        name="unique_doctor_schedule_per_day",
                    ),
                ),
            ],
            database_operations=[],
        ),
    ]
